<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="0" failures="0" file="test_store_access_log_tests.py" name="test_store_access_log_tests.TestStoreAccessLog-20210521125606" skipped="0" tests="4" time="0.184" timestamp="2021-05-21T12:56:09">
	<testcase classname="test_store_access_log_tests.TestStoreAccessLog" name="test_store_access_log_exists_ok" time="0.094" timestamp="2021-05-21T12:56:09"/>
	<testcase classname="test_store_access_log_tests.TestStoreAccessLog" name="test_store_access_log_not_exists_create_error" time="0.047" timestamp="2021-05-21T12:56:09"/>
	<testcase classname="test_store_access_log_tests.TestStoreAccessLog" name="test_store_access_log_not_exists_ok" time="0.033" timestamp="2021-05-21T12:56:09"/>
	<testcase classname="test_store_access_log_tests.TestStoreAccessLog" name="test_store_access_log_not_exists_write_error" time="0.009" timestamp="2021-05-21T12:56:09"/>
</testsuite>
